package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.ApplyCar;

import java.util.List;

public interface ApplyCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_car
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_car
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    int insert(ApplyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_car
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    int insertSelective(ApplyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_car
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    ApplyCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_car
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    int updateByPrimaryKeySelective(ApplyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_car
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    int updateByPrimaryKey(ApplyCar record);

    List<ApplyCar> selectAll();

    List<ApplyCar> selectAllByPhone(String who);
    List<ApplyCar> selectByStatus(Integer status);

}