package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.ApprovalCar;

public interface ApprovalCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_car
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_car
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int insert(ApprovalCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_car
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int insertSelective(ApprovalCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_car
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    ApprovalCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_car
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int updateByPrimaryKeySelective(ApprovalCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_car
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int updateByPrimaryKey(ApprovalCar record);
}