package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.AttendanceDetail;
import nju.software.convoy.data.entity.AttendanceDetailKey;

public interface AttendanceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_detail
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    int deleteByPrimaryKey(AttendanceDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_detail
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    int insert(AttendanceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_detail
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    int insertSelective(AttendanceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_detail
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    AttendanceDetail selectByPrimaryKey(AttendanceDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_detail
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    int updateByPrimaryKeySelective(AttendanceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_detail
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    int updateByPrimaryKey(AttendanceDetail record);
}