package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.Attendance;
import nju.software.convoy.data.entity.AttendanceDetail;
import nju.software.convoy.data.entity.AttendanceKey;

public interface AttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Jan 07 10:48:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Jan 07 10:48:22 CST 2020
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Jan 07 10:48:22 CST 2020
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Jan 07 10:48:22 CST 2020
     */
    Attendance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Jan 07 10:48:22 CST 2020
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Tue Jan 07 10:48:22 CST 2020
     */
    int updateByPrimaryKey(Attendance record);

    Attendance selectByDateAndDepartment(AttendanceKey key);
}