package nju.software.convoy.data.dao;

import com.github.pagehelper.Page;
import nju.software.convoy.data.entity.BusyCar;
import nju.software.convoy.service.model.CarStatusKey;
import nju.software.convoy.service.model.DriverStatusKey;

import java.util.List;

public interface BusyCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_car
     *
     * @mbg.generated Tue Apr 28 22:19:49 SGT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_car
     *
     * @mbg.generated Tue Apr 28 22:19:49 SGT 2020
     */
    int insert(BusyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_car
     *
     * @mbg.generated Tue Apr 28 22:19:49 SGT 2020
     */
    int insertSelective(BusyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_car
     *
     * @mbg.generated Tue Apr 28 22:19:49 SGT 2020
     */
    BusyCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_car
     *
     * @mbg.generated Tue Apr 28 22:19:49 SGT 2020
     */
    int updateByPrimaryKeySelective(BusyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_car
     *
     * @mbg.generated Tue Apr 28 22:19:49 SGT 2020
     */
    int updateByPrimaryKey(BusyCar record);

    List<BusyCar> selectStatusByPrimaryKey(CarStatusKey key);

    List<BusyCar> selectBusy(CarStatusKey key);
}