package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.BusyDriver;
import nju.software.convoy.service.model.CarStatusKey;
import nju.software.convoy.service.model.DriverStatusKey;

import java.util.List;

public interface BusyDriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_driver
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_driver
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int insert(BusyDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_driver
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int insertSelective(BusyDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_driver
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    BusyDriver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_driver
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int updateByPrimaryKeySelective(BusyDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table busy_driver
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int updateByPrimaryKey(BusyDriver record);

    List<BusyDriver> selectByDriver(String driver);

    List<BusyDriver> selectBusy(DriverStatusKey key);
}