package nju.software.convoy.data.dao;

import nju.software.convoy.controller.RequestBody.PageReq;
import nju.software.convoy.data.entity.Car;
import nju.software.convoy.controller.RequestBody.CarCondition;

import java.util.List;

public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    int insertSelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    Car selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    int updateByPrimaryKeySelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    int updateByPrimaryKey(Car record);

    List<Car> selectByKind(int kind);

    List<Car> selectByCondition(CarCondition condition);

    List<Car> selectAll();

    Integer getCount();
}