package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.Evaluation;

public interface EvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int insert(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluation
     *
     * @mbg.generated Wed Apr 29 18:28:50 SGT 2020
     */
    int insertSelective(Evaluation record);
}