package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.Holiday;

public interface HolidayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    int insert(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    int insertSelective(Holiday record);
}