package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.Holiday;
import nju.software.convoy.data.entity.HolidayKey;
import nju.software.convoy.data.entity.UserAuthorityKey;

import java.util.List;

public interface HolidayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int deleteByPrimaryKey(HolidayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int insert(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int insertSelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    Holiday selectByPrimaryKey(HolidayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int updateByPrimaryKeySelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int updateByPrimaryKey(Holiday record);

    List<Holiday> selectAuthority(UserAuthorityKey userAuthorityKey);
}