package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.Trip;
import nju.software.convoy.data.entity.TripKey;

public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int deleteByPrimaryKey(TripKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int insertSelective(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    Trip selectByPrimaryKey(TripKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int updateByPrimaryKeySelective(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    int updateByPrimaryKey(Trip record);
}