package nju.software.convoy.data.dao;

import nju.software.convoy.data.entity.Trip;

public interface TripMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    int insert(Trip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    int insertSelective(Trip record);
}