ALTER TABLE convoy.attendance MODIFY DATE DATE;

ALTER TABLE convoy.attendance_detail MODIFY TIME TIMESTAMP;

ALTER TABLE convoy.holiday MODIFY BEGIN TIMESTAMP;
ALTER TABLE convoy.holiday MODIFY END TIMESTAMP;
ALTER TABLE convoy.holiday MODIFY TIME TIMESTAMP;

ALTER TABLE convoy.trip MODIFY BEGIN DATE;
ALTER TABLE convoy.trip MODIFY END DATE;
ALTER TABLE convoy.trip MODIFY TIME TIMESTAMP;