ALTER TABLE convoy.attendance MODIFY DATE DATE;

ALTER TABLE convoy.attendance_detail MODIFY TIME TIMESTAMP;

ALTER TABLE convoy.holiday MODIFY BEGIN TIMESTAMP;
ALTER TABLE convoy.holiday MODIFY END TIMESTAMP;
ALTER TABLE convoy.holiday MODIFY TIME TIMESTAMP;

ALTER TABLE convoy.trip MODIFY BEGIN DATE;
ALTER TABLE convoy.trip MODIFY END DATE;
ALTER TABLE convoy.trip MODIFY TIME TIMESTAMP;

-- 不懂我当初为什么不加主键
ALTER TABLE convoy.trip ADD PRIMARY KEY (PHONE, BEGIN, END);
ALTER TABLE convoy.holiday ADD PRIMARY KEY (PHONE, BEGIN, END);

-- 2020.04.28 修改用户表，添加驾照字段
ALTER TABLE user ADD license int NULL;
