package nju.software.convoy.data.entity;

import lombok.ToString;

import java.util.Date;

@ToString
public class ApplyCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.ID
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.CAR_KIND
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private Integer carKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.START_TIME
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.END_TIME
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.START_POSITION
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private String startPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.END_POSITION
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private String endPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.FOLLOW
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private String follow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.REASON
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.WHO
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private String who;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.STATUS
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.DRIVER
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private String driver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_car.CAR
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    private Integer car;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.ID
     *
     * @return the value of apply_car.ID
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.ID
     *
     * @param id the value for apply_car.ID
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.CAR_KIND
     *
     * @return the value of apply_car.CAR_KIND
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public Integer getCarKind() {
        return carKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.CAR_KIND
     *
     * @param carKind the value for apply_car.CAR_KIND
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setCarKind(Integer carKind) {
        this.carKind = carKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.START_TIME
     *
     * @return the value of apply_car.START_TIME
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.START_TIME
     *
     * @param startTime the value for apply_car.START_TIME
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.END_TIME
     *
     * @return the value of apply_car.END_TIME
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.END_TIME
     *
     * @param endTime the value for apply_car.END_TIME
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.START_POSITION
     *
     * @return the value of apply_car.START_POSITION
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public String getStartPosition() {
        return startPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.START_POSITION
     *
     * @param startPosition the value for apply_car.START_POSITION
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setStartPosition(String startPosition) {
        this.startPosition = startPosition == null ? null : startPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.END_POSITION
     *
     * @return the value of apply_car.END_POSITION
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public String getEndPosition() {
        return endPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.END_POSITION
     *
     * @param endPosition the value for apply_car.END_POSITION
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setEndPosition(String endPosition) {
        this.endPosition = endPosition == null ? null : endPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.FOLLOW
     *
     * @return the value of apply_car.FOLLOW
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public String getFollow() {
        return follow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.FOLLOW
     *
     * @param follow the value for apply_car.FOLLOW
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setFollow(String follow) {
        this.follow = follow == null ? null : follow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.REASON
     *
     * @return the value of apply_car.REASON
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.REASON
     *
     * @param reason the value for apply_car.REASON
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.WHO
     *
     * @return the value of apply_car.WHO
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public String getWho() {
        return who;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.WHO
     *
     * @param who the value for apply_car.WHO
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setWho(String who) {
        this.who = who == null ? null : who.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.STATUS
     *
     * @return the value of apply_car.STATUS
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.STATUS
     *
     * @param status the value for apply_car.STATUS
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.DRIVER
     *
     * @return the value of apply_car.DRIVER
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.DRIVER
     *
     * @param driver the value for apply_car.DRIVER
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_car.CAR
     *
     * @return the value of apply_car.CAR
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public Integer getCar() {
        return car;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_car.CAR
     *
     * @param car the value for apply_car.CAR
     *
     * @mbg.generated Tue Apr 28 21:21:23 SGT 2020
     */
    public void setCar(Integer car) {
        this.car = car;
    }
}