package nju.software.convoy.data.entity;

public class AttendanceDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.ATT_ID
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    private Integer attId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.PHONE
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.ATT_ID
     *
     * @return the value of attendance_detail.ATT_ID
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public Integer getAttId() {
        return attId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.ATT_ID
     *
     * @param attId the value for attendance_detail.ATT_ID
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public void setAttId(Integer attId) {
        this.attId = attId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.PHONE
     *
     * @return the value of attendance_detail.PHONE
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.PHONE
     *
     * @param phone the value for attendance_detail.PHONE
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}