package nju.software.convoy.data.entity;

import java.util.Date;

// 考勤详情
public class AttendanceDetail extends AttendanceDetailKey {
    /**
     * 姓名
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.NAME
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    private String name;

    /**
     * 位置
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.ADDRESS
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    private String address;

    /**
     * 考勤时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.TIME
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.NAME
     *
     * @return the value of attendance_detail.NAME
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.NAME
     *
     * @param name the value for attendance_detail.NAME
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.ADDRESS
     *
     * @return the value of attendance_detail.ADDRESS
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.ADDRESS
     *
     * @param address the value for attendance_detail.ADDRESS
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.TIME
     *
     * @return the value of attendance_detail.TIME
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.TIME
     *
     * @param time the value for attendance_detail.TIME
     *
     * @mbg.generated Thu Jan 16 13:28:12 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}