package nju.software.convoy.data.entity;

import lombok.ToString;

@ToString
public class AttendanceDetail extends AttendanceDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.NAME
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.ADDRESS
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_detail.TIME
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.NAME
     *
     * @return the value of attendance_detail.NAME
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.NAME
     *
     * @param name the value for attendance_detail.NAME
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.ADDRESS
     *
     * @return the value of attendance_detail.ADDRESS
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.ADDRESS
     *
     * @param address the value for attendance_detail.ADDRESS
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_detail.TIME
     *
     * @return the value of attendance_detail.TIME
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_detail.TIME
     *
     * @param time the value for attendance_detail.TIME
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}