package nju.software.convoy.data.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.util.Date;

@AllArgsConstructor
//@NoArgsConstructor
public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.ID
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.KIND
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Integer kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.NUMBER_PLATE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private String numberPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.MODEL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.PEOPLE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.COLOR
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.LOAD_WEIGHT
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Integer loadWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.FUEL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Integer fuel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.SERVICE_START
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Date serviceStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.INSPECT
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Date inspect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.INSPECT_DDL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Date inspectDdl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.SAFE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Date safe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.SAFE_DDL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    private Date safeDdl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.ID
     *
     * @return the value of car.ID
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.ID
     *
     * @param id the value for car.ID
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.KIND
     *
     * @return the value of car.KIND
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Integer getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.KIND
     *
     * @param kind the value for car.KIND
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setKind(Integer kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.NUMBER_PLATE
     *
     * @return the value of car.NUMBER_PLATE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public String getNumberPlate() {
        return numberPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.NUMBER_PLATE
     *
     * @param numberPlate the value for car.NUMBER_PLATE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setNumberPlate(String numberPlate) {
        this.numberPlate = numberPlate == null ? null : numberPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.MODEL
     *
     * @return the value of car.MODEL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.MODEL
     *
     * @param model the value for car.MODEL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.PEOPLE
     *
     * @return the value of car.PEOPLE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.PEOPLE
     *
     * @param people the value for car.PEOPLE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.COLOR
     *
     * @return the value of car.COLOR
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.COLOR
     *
     * @param color the value for car.COLOR
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.LOAD_WEIGHT
     *
     * @return the value of car.LOAD_WEIGHT
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Integer getLoadWeight() {
        return loadWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.LOAD_WEIGHT
     *
     * @param loadWeight the value for car.LOAD_WEIGHT
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setLoadWeight(Integer loadWeight) {
        this.loadWeight = loadWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.FUEL
     *
     * @return the value of car.FUEL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Integer getFuel() {
        return fuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.FUEL
     *
     * @param fuel the value for car.FUEL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setFuel(Integer fuel) {
        this.fuel = fuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.SERVICE_START
     *
     * @return the value of car.SERVICE_START
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Date getServiceStart() {
        return serviceStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.SERVICE_START
     *
     * @param serviceStart the value for car.SERVICE_START
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setServiceStart(Date serviceStart) {
        this.serviceStart = serviceStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.INSPECT
     *
     * @return the value of car.INSPECT
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Date getInspect() {
        return inspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.INSPECT
     *
     * @param inspect the value for car.INSPECT
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setInspect(Date inspect) {
        this.inspect = inspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.INSPECT_DDL
     *
     * @return the value of car.INSPECT_DDL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Date getInspectDdl() {
        return inspectDdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.INSPECT_DDL
     *
     * @param inspectDdl the value for car.INSPECT_DDL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setInspectDdl(Date inspectDdl) {
        this.inspectDdl = inspectDdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.SAFE
     *
     * @return the value of car.SAFE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Date getSafe() {
        return safe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.SAFE
     *
     * @param safe the value for car.SAFE
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setSafe(Date safe) {
        this.safe = safe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.SAFE_DDL
     *
     * @return the value of car.SAFE_DDL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public Date getSafeDdl() {
        return safeDdl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.SAFE_DDL
     *
     * @param safeDdl the value for car.SAFE_DDL
     *
     * @mbg.generated Tue Apr 28 08:49:08 SGT 2020
     */
    public void setSafeDdl(Date safeDdl) {
        this.safeDdl = safeDdl;
    }
}