package nju.software.convoy.data.entity;

import java.util.Date;

public class Holiday extends HolidayKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.APPROVE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private Byte approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.DEPARTMENT
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.TYPE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.REASON
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.TIME
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.APPROVE
     *
     * @return the value of holiday.APPROVE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public Byte getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.APPROVE
     *
     * @param approve the value for holiday.APPROVE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setApprove(Byte approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.DEPARTMENT
     *
     * @return the value of holiday.DEPARTMENT
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.DEPARTMENT
     *
     * @param department the value for holiday.DEPARTMENT
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.TYPE
     *
     * @return the value of holiday.TYPE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.TYPE
     *
     * @param type the value for holiday.TYPE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.REASON
     *
     * @return the value of holiday.REASON
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.REASON
     *
     * @param reason the value for holiday.REASON
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.TIME
     *
     * @return the value of holiday.TIME
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.TIME
     *
     * @param time the value for holiday.TIME
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}