package nju.software.convoy.data.entity;

public class Holiday {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.PHONE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.BEGIN
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private String begin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.END
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private String end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.APPROVE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private Byte approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.DEPARTMENT
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.TYPE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.REASON
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.TIME
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.PHONE
     *
     * @return the value of holiday.PHONE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.PHONE
     *
     * @param phone the value for holiday.PHONE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.BEGIN
     *
     * @return the value of holiday.BEGIN
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public String getBegin() {
        return begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.BEGIN
     *
     * @param begin the value for holiday.BEGIN
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setBegin(String begin) {
        this.begin = begin == null ? null : begin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.END
     *
     * @return the value of holiday.END
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.END
     *
     * @param end the value for holiday.END
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.APPROVE
     *
     * @return the value of holiday.APPROVE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public Byte getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.APPROVE
     *
     * @param approve the value for holiday.APPROVE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setApprove(Byte approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.DEPARTMENT
     *
     * @return the value of holiday.DEPARTMENT
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.DEPARTMENT
     *
     * @param department the value for holiday.DEPARTMENT
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.TYPE
     *
     * @return the value of holiday.TYPE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.TYPE
     *
     * @param type the value for holiday.TYPE
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.REASON
     *
     * @return the value of holiday.REASON
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.REASON
     *
     * @param reason the value for holiday.REASON
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.TIME
     *
     * @return the value of holiday.TIME
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.TIME
     *
     * @param time the value for holiday.TIME
     *
     * @mbg.generated Thu Jan 09 09:51:10 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}