package nju.software.convoy.data.entity;

import java.util.Date;

public class HolidayKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.PHONE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.BEGIN
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private Date begin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.END
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    private Date end;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.PHONE
     *
     * @return the value of holiday.PHONE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.PHONE
     *
     * @param phone the value for holiday.PHONE
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.BEGIN
     *
     * @return the value of holiday.BEGIN
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public Date getBegin() {
        return begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.BEGIN
     *
     * @param begin the value for holiday.BEGIN
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setBegin(Date begin) {
        this.begin = begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.END
     *
     * @return the value of holiday.END
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.END
     *
     * @param end the value for holiday.END
     *
     * @mbg.generated Wed Jan 22 14:39:00 CST 2020
     */
    public void setEnd(Date end) {
        this.end = end;
    }
}