package nju.software.convoy.data.entity;

public class Trip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip.PHONE
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip.BEGIN
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String begin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip.END
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip.APPROVE
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private Byte approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip.DEPARTMENT
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip.ADDRESS
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trip.PHONE
     *
     * @return the value of trip.PHONE
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trip.PHONE
     *
     * @param phone the value for trip.PHONE
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trip.BEGIN
     *
     * @return the value of trip.BEGIN
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getBegin() {
        return begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trip.BEGIN
     *
     * @param begin the value for trip.BEGIN
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setBegin(String begin) {
        this.begin = begin == null ? null : begin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trip.END
     *
     * @return the value of trip.END
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trip.END
     *
     * @param end the value for trip.END
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trip.APPROVE
     *
     * @return the value of trip.APPROVE
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public Byte getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trip.APPROVE
     *
     * @param approve the value for trip.APPROVE
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setApprove(Byte approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trip.DEPARTMENT
     *
     * @return the value of trip.DEPARTMENT
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trip.DEPARTMENT
     *
     * @param department the value for trip.DEPARTMENT
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trip.ADDRESS
     *
     * @return the value of trip.ADDRESS
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trip.ADDRESS
     *
     * @param address the value for trip.ADDRESS
     *
     * @mbg.generated Thu Jan 02 17:06:54 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}