package nju.software.convoy.data.entity;

public class User {

    public User(String phone, String password, String department, int title, String name, String titleDes){
        this.setPhone(phone);
        this.setDepartment(department);
        this.setName(name);
        this.setTitle(title);
        this.setTitleDes(titleDes);
        this.setPassword(password);
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PHONE
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DEPARTMENT
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TITLE
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    private Integer title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NAME
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.TITLE_DES
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    private String titleDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.IMG
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    private byte[] img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PHONE
     *
     * @return the value of user.PHONE
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PHONE
     *
     * @param phone the value for user.PHONE
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DEPARTMENT
     *
     * @return the value of user.DEPARTMENT
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DEPARTMENT
     *
     * @param department the value for user.DEPARTMENT
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TITLE
     *
     * @return the value of user.TITLE
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public Integer getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TITLE
     *
     * @param title the value for user.TITLE
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public void setTitle(Integer title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NAME
     *
     * @return the value of user.NAME
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NAME
     *
     * @param name the value for user.NAME
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.TITLE_DES
     *
     * @return the value of user.TITLE_DES
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public String getTitleDes() {
        return titleDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.TITLE_DES
     *
     * @param titleDes the value for user.TITLE_DES
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public void setTitleDes(String titleDes) {
        this.titleDes = titleDes == null ? null : titleDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.IMG
     *
     * @return the value of user.IMG
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public byte[] getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.IMG
     *
     * @param img the value for user.IMG
     *
     * @mbg.generated Thu Jan 09 10:59:48 CST 2020
     */
    public void setImg(byte[] img) {
        this.img = img;
    }
}